# Copyright (c) MLLM Team.
# Licensed under the MIT License.
"""Generate Spark tokenizer Unicode property ranges using regex 2026.1.15."""
import regex
if regex.__version__ != "2026.1.15":
    raise RuntimeError("Regeneration requires regex==2026.1.15")
from pathlib import Path
patterns = [regex.compile(r"\p{" + p + "}") for p in ["L", "M", "P", "S", "N", "Nd", "White_Space"]]
ranges = []
start = 0
last = 0
for cp in range(0x110001):
    flags = sum(1 << i for i, p in enumerate(patterns) if cp < 0x110000 and p.fullmatch(chr(cp)))
    if flags != last:
        if last:
            ranges.append((start, cp - 1, last))
        start, last = cp, flags
out = Path(__file__).resolve().parents[2] / "mllm/models/spark2_5/unicode_ranges.hpp"
with out.open("w") as f:
    f.write("// Copyright (c) MLLM Team.\n// Licensed under the MIT License.\n// Generated by examples/spark2_5/generate_unicode_ranges.py; regex " + regex.__version__ + ".\n#pragma once\n#include <cstdint>\n#include <iterator>\nnamespace mllm::models::spark2_5 {\nstruct UnicodeRange { uint32_t first, last; uint8_t flags; };\ninline constexpr UnicodeRange unicode_ranges[] = {\n")
    for a, b, v in ranges:
        f.write(f"  {{0x{a:X}, 0x{b:X}, {v}}},\n")
    f.write("};\ninline uint8_t unicodeFlags(uint32_t cp) {\n  size_t l=0,r=std::size(unicode_ranges);\n  while(l<r) { auto m=(l+r)/2; if(unicode_ranges[m].last<cp) l=m+1; else r=m; }\n  return l<std::size(unicode_ranges) && unicode_ranges[l].first<=cp ? unicode_ranges[l].flags : 0;\n}\n}  // namespace mllm::models::spark2_5\n")
