// Copyright (c) MLLM Team.
// Licensed under the MIT License.

// GENERATED BY AGENT !!!
// SHOULD REVIEW AGAIN !!!

#pragma once

#include <nlohmann/json_fwd.hpp>
#include "mllm/compile/ir/linalg/Op.hpp"

namespace mllm::jit::binary {

nlohmann::json dumpLinalgIROptions(const ir::linalg::LinalgIROp::ptr_t& op);

// Function declarations for each LinalgIR operation
nlohmann::json dumpFillOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpAddOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpSubOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpMulOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpDivOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpAbsOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpLogOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpMatMulOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpEmbeddingOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpLinearOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpRoPEOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpKVCacheOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpCausalMaskOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpSoftmaxOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpTransposeOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpRMSNormOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpSiLUOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpCastTypeOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpX2XOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpViewOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpSplitOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpSTFTOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpFlashAttention2OpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpRepeatOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpPermuteOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpConv1DOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpConv2DOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpConv3DOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpGELUOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpLayerNormOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpMultimodalRoPEOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpVisionRoPEOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpQuickGELUOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpCopyOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpCloneOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpNegOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpConcatOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpReduceMaxOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpReduceMinOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpReduceSumOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpReLUOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpContiguousOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpReshapeOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpSliceOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpParamOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpIndexOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpTopKOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpMeanOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);
nlohmann::json dumpClipOpIROptions(const ir::linalg::LinalgIROp::ptr_t& op);

}  // namespace mllm::jit::binary
