#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* causal_mask = "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
                          "__kernel void causal_mask_fp32(__global const float *input,\n"
                          " __global float *output,const int B,const int H,\n"
                          " const int S,const int D,\n"
                          " const int sliding_window,\n"
                          " const int window_size) {\n"
                          " const int d=get_global_id(0);\n"
                          " const int s=get_global_id(1);\n"
                          " const int bh=get_global_id(2);\n"
                          " if (d >= D || s >= S || bh >= B*H) {\n"
                          " return;\n"
                          " }\n"
                          " const int offset=(bh*S+s)*D+d;\n"
                          " float val=input[offset];\n"
                          " if (S == 1) {\n"
                          " output[offset]=val;\n"
                          " return;\n"
                          " }\n"
                          " if (sliding_window == 0) {\n"
                          " // Standard causal mask\n"
                          " int copy_count=D-S+s+1;\n"
                          " if (d >= copy_count) {\n"
                          " val=-1e10f;\n"
                          " }\n"
                          " } else {\n"
                          " // Sliding window\n"
                          " int copy_start_idx=s-window_size+1;\n"
                          " if (copy_start_idx<0)\n"
                          " copy_start_idx=0;\n"
                          " int copy_end_idx=s+1;\n"
                          " if (d<copy_start_idx || d >= copy_end_idx) {\n"
                          " val=-1e10f;\n"
                          " }\n"
                          " }\n"
                          " output[offset]=val;\n"
                          "}\n"
                          "__kernel void causal_mask_fp16(__global const half *input,\n"
                          " __global half *output,const int B,const int H,\n"
                          " const int S,const int D,\n"
                          " const int sliding_window,\n"
                          " const int window_size) {\n"
                          " const int d=get_global_id(0);\n"
                          " const int s=get_global_id(1);\n"
                          " const int bh=get_global_id(2);\n"
                          " if (d >= D || s >= S || bh >= B*H) {\n"
                          " return;\n"
                          " }\n"
                          " const int offset=(bh*S+s)*D+d;\n"
                          " half val=input[offset];\n"
                          " if (S == 1) {\n"
                          " output[offset]=val;\n"
                          " return;\n"
                          " }\n"
                          " if (sliding_window == 0) {\n"
                          " int copy_count=D-S+s+1;\n"
                          " if (d >= copy_count) {\n"
                          " val=-65500.0h;\n"
                          " }\n"
                          " } else {\n"
                          " int copy_start_idx=s-window_size+1;\n"
                          " if (copy_start_idx<0)\n"
                          " copy_start_idx=0;\n"
                          " int copy_end_idx=s+1;\n"
                          " if (d<copy_start_idx || d >= copy_end_idx) {\n"
                          " val=-65500.0h;\n"
                          " }\n"
                          " }\n"
                          " output[offset]=val;\n"
                          "}\n";
}  // namespace mllm::opencl
