#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* div = "__kernel void div_float(__global const float *A,__global const float *B,\n"
                  " __global float *C) {\n"
                  " size_t index=get_global_id(0);\n"
                  " C[index]=A[index]/B[index];\n"
                  "}\n"
                  "__kernel void div_broadcast_float(__global const float *A,__global const float *B,__global float *C,\n"
                  " int batch_size,int loop_size,int vector_size,\n"
                  " int batch_stride_a,int loop_stride_a,\n"
                  " int batch_stride_b,int loop_stride_b) {\n"
                  " int global_id=get_global_id(0);\n"
                  " \n"
                  " int v=global_id % vector_size;\n"
                  " int tmp=global_id/vector_size;\n"
                  " int l=tmp % loop_size;\n"
                  " int b=tmp/loop_size;\n"
                  " \n"
                  " if (b >= batch_size) return;\n"
                  " int offset_a=b*batch_stride_a+l*loop_stride_a+v;\n"
                  " int offset_b=b*batch_stride_b+l*loop_stride_b+v;\n"
                  " \n"
                  " C[global_id]=A[offset_a]/B[offset_b];\n"
                  "}\n";
}  // namespace mllm::opencl
