#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* matmul = "__kernel void matmul_buffer_nt_nt(const int M,const int N,const int K,\n"
                     " __global float *A,const int A_batch_stride,\n"
                     " __global float *B,const int B_batch_stride,\n"
                     " __global float *C,const int C_batch_stride) {\n"
                     " const int m=get_global_id(0);\n"
                     " const int n=get_global_id(1);\n"
                     " const int b=get_global_id(2);\n"
                     " if (m >= M || n >= N)\n"
                     " return;\n"
                     " const int a_offset=b*A_batch_stride;\n"
                     " const int b_offset=b*B_batch_stride;\n"
                     " const int c_offset=b*C_batch_stride;\n"
                     " float sum=0.0f;\n"
                     " for (int k=0; k<K; ++k) {\n"
                     " sum += A[a_offset+m*K+k]*B[b_offset+k*N+n];\n"
                     " }\n"
                     " C[c_offset+m*N+n]=sum;\n"
                     "}\n"
                     "__kernel void matmul_buffer_nt_t(const int M,const int N,const int K,\n"
                     " __global float *A,const int A_batch_stride,\n"
                     " __global float *B,const int B_batch_stride,\n"
                     " __global float *C,const int C_batch_stride) {\n"
                     " const int m=get_global_id(0);\n"
                     " const int n=get_global_id(1);\n"
                     " const int b=get_global_id(2);\n"
                     " if (m >= M || n >= N)\n"
                     " return;\n"
                     " const int a_offset=b*A_batch_stride;\n"
                     " const int b_offset=b*B_batch_stride;\n"
                     " const int c_offset=b*C_batch_stride;\n"
                     " float sum=0.0f;\n"
                     " for (int k=0; k<K; ++k) {\n"
                     " sum += A[a_offset+m*K+k]*B[b_offset+n*K+k];\n"
                     " }\n"
                     " C[c_offset+m*N+n]=sum;\n"
                     "}\n";
}  // namespace mllm::opencl
