#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* rope = "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
                   "__kernel void rope_f32(__global const float *src,__global float *dst,\n"
                   " __global const float *sin_table,\n"
                   " __global const float *cos_table,const int H,\n"
                   " const int S,const int D) {\n"
                   " int d_half=get_global_id(0);\n"
                   " int s=get_global_id(1);\n"
                   " int bh=get_global_id(2);\n"
                   " if (d_half >= D/2)\n"
                   " return;\n"
                   " int b=bh/H;\n"
                   " int h=bh % H;\n"
                   " int d=d_half;\n"
                   " int d_pair=d+D/2;\n"
                   " // Input shape: [B,H,S,D]\n"
                   " int in_idx1=b*(H*S*D)+h*(S*D)+s*D+d;\n"
                   " int in_idx2=b*(H*S*D)+h*(S*D)+s*D+d_pair;\n"
                   " // Sin/Cos shape: [B,S,D]\n"
                   " int sc_idx1=b*(S*D)+s*D+d;\n"
                   " float v1=src[in_idx1];\n"
                   " float v2=src[in_idx2];\n"
                   " float s1=sin_table[sc_idx1];\n"
                   " float c1=cos_table[sc_idx1];\n"
                   " float out1=v1*c1-v2*s1;\n"
                   " float out2=v1*s1+v2*c1;\n"
                   " dst[in_idx1]=out1;\n"
                   " dst[in_idx2]=out2;\n"
                   "}\n"
                   "__kernel void rope_f16(__global const half *src,__global half *dst,\n"
                   " __global const float *sin_table,\n"
                   " __global const float *cos_table,const int H,\n"
                   " const int S,const int D) {\n"
                   " int d_half=get_global_id(0);\n"
                   " int s=get_global_id(1);\n"
                   " int bh=get_global_id(2);\n"
                   " if (d_half >= D/2)\n"
                   " return;\n"
                   " int b=bh/H;\n"
                   " int h=bh % H;\n"
                   " int d=d_half;\n"
                   " int d_pair=d+D/2;\n"
                   " // Input shape: [B,H,S,D]\n"
                   " int in_idx1=b*(H*S*D)+h*(S*D)+s*D+d;\n"
                   " int in_idx2=b*(H*S*D)+h*(S*D)+s*D+d_pair;\n"
                   " // Sin/Cos shape: [B,S,D]\n"
                   " int sc_idx1=b*(S*D)+s*D+d;\n"
                   " float v1=(float)src[in_idx1];\n"
                   " float v2=(float)src[in_idx2];\n"
                   " float s1=sin_table[sc_idx1];\n"
                   " float c1=cos_table[sc_idx1];\n"
                   " float out1=v1*c1-v2*s1;\n"
                   " float out2=v1*s1+v2*c1;\n"
                   " dst[in_idx1]=(half)out1;\n"
                   " dst[in_idx2]=(half)out2;\n"
                   "}\n";
}  // namespace mllm::opencl
