#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* silu = "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
                   "__kernel void silu_fp32(__global const float *input,__global float *output) {\n"
                   " const int i=get_global_id(0);\n"
                   " const float x=input[i];\n"
                   " output[i]=x/(1.0f+exp(-x));\n"
                   "}\n"
                   "__kernel void silu_fp16(__global const half *input,__global half *output,\n"
                   " const int count) {\n"
                   " const int vec_idx=get_global_id(0);\n"
                   " const int vec_limit=count/4;\n"
                   " if (vec_idx<vec_limit) {\n"
                   " const int i=vec_idx*4;\n"
                   " half4 x=vload4(0,input+i);\n"
                   " half4 result=x/((half4)(1.0h)+exp(-x));\n"
                   " vstore4(result,0,output+i);\n"
                   " }\n"
                   " const int remainder_start=vec_limit*4;\n"
                   " if (get_local_id(0)<(count-remainder_start) && get_group_id(0) == 0) {\n"
                   " const int i=remainder_start+get_local_id(0);\n"
                   " if (i<count) {\n"
                   " const half x=input[i];\n"
                   " output[i]=x/(1.0h+exp(-x));\n"
                   " }\n"
                   " }\n"
                   "}\n";
}  // namespace mllm::opencl
