#include "a_opencl_source_map.hpp"
namespace mllm::opencl {
const char* transpose = "__kernel void transpose_generic(__global const float *input,\n"
                        " __global float *output,\n"
                        " __global const int *in_strides,\n"
                        " __global const int *out_shape,\n"
                        " __global const int *perm,const int ndim,\n"
                        " const int total_elements) {\n"
                        " int global_id=get_global_id(0);\n"
                        " if (global_id >= total_elements)\n"
                        " return;\n"
                        " int temp_idx=global_id;\n"
                        " int in_idx=0;\n"
                        " for (int i=0; i<ndim; ++i) {\n"
                        " int d=ndim-1-i;\n"
                        " int coord=temp_idx % out_shape[d];\n"
                        " temp_idx /= out_shape[d];\n"
                        " in_idx += coord*in_strides[perm[d]];\n"
                        " }\n"
                        " output[global_id]=input[in_idx];\n"
                        "}\n"
                        "__kernel void transpose_0213(__global const float *input,\n"
                        " __global float *output,const int B,const int S,\n"
                        " const int H,const int D) {\n"
                        " int global_id=get_global_id(0);\n"
                        " int total=B*S*H*D;\n"
                        " if (global_id >= total)\n"
                        " return;\n"
                        " int d=global_id % D;\n"
                        " int temp=global_id/D;\n"
                        " int s=temp % S;\n"
                        " temp=temp/S;\n"
                        " int h=temp % H;\n"
                        " int b=temp/H;\n"
                        " int in_idx=((b*S+s)*H+h)*D+d;\n"
                        " output[global_id]=input[in_idx];\n"
                        "}\n"
                        "__kernel void transpose_0132(__global const float *input,\n"
                        " __global float *output,const int B,const int C,\n"
                        " const int H,const int W) {\n"
                        " int global_id=get_global_id(0);\n"
                        " int total=B*C*H*W;\n"
                        " if (global_id >= total)\n"
                        " return;\n"
                        " int h=global_id % H;\n"
                        " int temp=global_id/H;\n"
                        " int w=temp % W;\n"
                        " temp=temp/W;\n"
                        " int c=temp % C;\n"
                        " int b=temp/C;\n"
                        " int in_idx=((b*C+c)*H+h)*W+w;\n"
                        " output[global_id]=input[in_idx];\n"
                        "}\n";
}  // namespace mllm::opencl
