name: 🐞 Bug Report
description: Create a bug report to help us improve the MLLM framework.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you have completed the following steps before submitting your report.
      options:
        - label: I have searched the existing issues and confirmed this is not a duplicate.
          required: true
        - label: I am using the latest version of the MLLM framework.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of what the bug is.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the specific steps needed to reproduce this bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the result you were expecting.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: On which operating system did you encounter this issue?
      options:
        - Android
        - iOS
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: Please provide the model of the device where you encountered the issue.
      placeholder: "e.g., Pixel 8 Pro, iPhone 15 Pro, AMD 9900X, Intel Xeon Processor"
    validations:
      required: true
  - type: input
    id: mllm-version
    attributes:
      label: MLLM Framework Version
      description: Which version of the MLLM framework are you using?
      placeholder: "e.g., v1.2.0"
    validations:
      required: true
  - type: textarea
    id: model-information
    attributes:
      label: Model Information
      description: If this bug is related to a specific model, please provide its details (e.g., model name, source, quantization type).
      placeholder: "e.g., Gemma 2B, from..., INT8 quantization"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
