FROM nvcr.io/nvidia/pytorch:24.05-py3

WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive \
    LC_ALL=en_US.UTF-8 \
    PATH="/opt/conda/bin:$PATH"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git \
    wget \
    unzip \
    doxygen \
    graphviz \
    llvm-dev \
    ninja-build \
    libtinfo-dev \
    zlib1g-dev \
    libedit-dev \
    libxml2-dev \
    ca-certificates \
    android-tools-adb \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh

# Install conda packages
RUN conda install -y pip cmake && \
    conda install -c conda-forge libstdcxx-ng=12 && \
    conda clean --all

RUN git clone --recursive https://github.com/UbiquitousLearning/mllm.git

CMD bash
