printf "# date: $(date)\n" > AUTHORS
printf "# this file is auto-generated by scripts/gen-authors.sh\n\n" >> AUTHORS

git log --format='%an <%ae>' --reverse --date=short v2 | awk '!seen[$0]++' | sort >> AUTHORS
