function(mllm_configure_blas)
  set(MLLM_BLAS_COMPILE_DEFINITIONS "" PARENT_SCOPE)
  set(MLLM_BLAS_LIBRARIES "" PARENT_SCOPE)
  set(MLLM_BLAS_INCLUDE_DIRS "" PARENT_SCOPE)
  if(APPLE and MLLM_BLAS_VENDOR_ACCELERATE)
    find_library(ACCELERATE_FRAMEWORK Accelerate)
    if(ACCELERATE_FRAMEWORK)
      set(BLAS_LIBRARIES ${ACCELERATE_FRAMEWORK} PARENT_SCOPE)
      set(BLAS_COMPILE_DEFINITIONS MLLM_USE_ACCELERATE PARENT_SCOPE)
      message(STATUS "Found Apple Accelerate framework: ${ACCELERATE_FRAMEWORK}")
    else()
      message(WARNING "Apple Accelerate framework not found")
    endif()
  endif()
endfunction()